export const WORLD_CUP_TEAMS = [
  'Canada', 'Mexico', 'United States',
  'Australia', 'Iran', 'Japan', 'Jordan', 'South Korea', 'Qatar', 'Saudi Arabia', 'Uzbekistan',
  'Algeria', 'Cape Verde', 'Egypt', 'Ghana', 'Ivory Coast', 'Morocco', 'Senegal', 'South Africa', 'Tunisia',
  'Curaçao', 'Haiti', 'Panama',
  'Argentina', 'Brazil', 'Colombia', 'Ecuador', 'Paraguay', 'Uruguay',
  'New Zealand',
  'Austria', 'Belgium', 'Croatia', 'England', 'France', 'Germany', 'Netherlands',
  'Norway', 'Portugal', 'Scotland', 'Spain', 'Switzerland',
]

export const TEAM_TO_FLAG_CODE = {
  Canada: 'ca',
  Mexico: 'mx',
  'United States': 'us',
  Australia: 'au',
  Iran: 'ir',
  Japan: 'jp',
  Jordan: 'jo',
  'South Korea': 'kr',
  Qatar: 'qa',
  'Saudi Arabia': 'sa',
  Uzbekistan: 'uz',
  Algeria: 'dz',
  'Cape Verde': 'cv',
  Egypt: 'eg',
  Ghana: 'gh',
  'Ivory Coast': 'ci',
  Morocco: 'ma',
  Senegal: 'sn',
  'South Africa': 'za',
  Tunisia: 'tn',
  Curaçao: 'cw',
  Haiti: 'ht',
  Panama: 'pa',
  Argentina: 'ar',
  Brazil: 'br',
  Colombia: 'co',
  Ecuador: 'ec',
  Paraguay: 'py',
  Uruguay: 'uy',
  'New Zealand': 'nz',
  Austria: 'at',
  Belgium: 'be',
  Croatia: 'hr',
  England: 'gb-eng',
  France: 'fr',
  Germany: 'de',
  Netherlands: 'nl',
  Norway: 'no',
  Portugal: 'pt',
  Scotland: 'gb-sct',
  Spain: 'es',
  Switzerland: 'ch',
}
